language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-2_gaviushova_lab
  - make -j
 # - cd ./bin/
  - ./vector/vector
notifications:
  email: false
