language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-2_gavriushova_lab
  - make -j
  - ./matrixtest/matrixtest
notifications:
  email: false
